Zephyr v2.7.0 bugfix null callback
meulemanelectronics/zephyr pull request #2
Opened 2022-06-07 08:39 UTC by christopher-clingerman

In case of a sudden disconnect, the `cb()` function pointer can be NULL, leading to an "illegal use of the EPSR" kernel fault.  The other change is to remove an assertion that could potentially trigger (also) in the case of a sudden disconnect.

2022-06-08 13:11 UTC, jpsaman requested changes

2022-06-08 13:11 UTC, jpsaman commented on subsys/bluetooth/host/conn.c
> +		if (cb == NULL) {
It is better to write 
```
if (cb) {
    cb(conn, user_data);
}
```

2022-06-08 13:11 UTC, jpsaman commented on subsys/bluetooth/controller/ll_sw/ull_conn.c
> +			//LL_ASSERT(!link->next);
This whole part should be rewritten as
```
                if (tx) {
		    /* release ctrl mem if points to itself */           
		    if (link->next == (void *)tx) {
			LL_ASSERT(link->next);

			mem_release(tx, &mem_conn_tx_ctrl.free);
                    }
		} else {
			/* Tx Node re-used to enqueue new ctrl PDU */
		}
```

2022-06-13 14:38 UTC, jpsaman approved these changes
Please make another PR for upstreaming to Zephyr.

2022-06-14 06:33 UTC, christopher-clingerman commented
> Please make another PR for upstreaming to Zephyr.

I have yet to do the first one due to how busy things have been.  I will probably combine all of these changes so far in one PR if that makes sense to you to do so.

2022-06-14 06:34 UTC, merged